#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

if [ "$(uname -s)" == "Darwin" ]
then
  echo "› brew bundle"
  brew bundle
else
  sudo apt-get update  
fi


# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
